### ISSUE TITLE
how to call a unexported Func in a struct?

### ISSUE THREAD

**Issue by hzmsrv** [alangpierce/go-forceexport#1]
how to call a unexported Func in a struct?

**Comment by alangpierce** [comment]
You can use the `reflect` package for to access unexported fields/methods on structs. This `go-forceexport` package is only useful for accessing top-level functions (which `reflect` can't do).

For example, see this stackoverflow answer, which I think can be used to access unexported names:
http://stackoverflow.com/questions/8103617/call-a-struct-and-its-method-by-name-in-go

**Comment by hzmsrv** [comment]
unexported func can not be call

**Comment by alangpierce** [comment]
Ok, I thought it was possible to use `reflect` to access unexported methods, but I might be remembering wrong, and I don't have an easy way to test it right now (I haven't been using Go recently). Probably you should ask on StackOverflow and include what code you tried.
